### ISSUE TITLE
Variable $status-error

### ISSUE THREAD

**Issue by ghost** [rC5HUaxv9j/Gekijou#1]
![image](https://user-images.githubusercontent.com/33172909/229305479-995fc1fe-4ff2-449a-939e-70dcb0ce0bb2.png)

This project looks very promising, but sadly I ran into this error

**Comment by CoolLaugh** [comment]
Thanks for trying my program.  Are you getting this error outside of the browse or recommendation tab?  Its been fixed for those tabs but the change hasn't made it to a release yet.

**Comment by ghost** [comment]
I'm not sure actually as I just switched from the settings page to just random tab and can't remember which one it was. It probably was very likely the "Recommended"-tab.

I'm guessing it's separate issue that all I see is blank tabs? I've ran into that in past on other programs too due to how many animes I have on my list

**Comment by CoolLaugh** [comment]
Double check if your user name is correct and the authorization code is entered.  Number of animes isn't an issue, I've already tested 1000+ long lists.

**Comment by ghost** [comment]
It seems to work now, I think it could have been me running into rate limiting due to refreshing metadata on Jellyfin.. I think some sort of popup for being rate limited would be useful in the future updates?
Not that many people would even hit that limit but should atleast be considered
